#!/bin/sh
. "venv/bin/activate"
python args_get_urls_by_tab.py -tn "Cambodia condominiums"
python args_dt_dotproperty-1.py -tn "Cambodia condominiums"
python args_dt_load_to_sheet.py -tn "Cambodia condominiums"
python args_dt_dotproperty-2.py -tn "Cambodia condominiums"
python args_dt_dotproperty-mix.py -tn "Cambodia condominiums"
python args_get_urls_by_tab.py -tn "Cambodia houses"
python args_dt_dotproperty-1.py -tn "Cambodia houses"
python args_dt_load_to_sheet.py -tn "Cambodia houses"
python args_dt_dotproperty-2.py -tn "Cambodia houses"
python args_dt_dotproperty-mix.py -tn "Cambodia houses"
python args_get_urls_by_tab.py -tn "Cambodia townhouses"
python args_dt_dotproperty-1.py -tn "Cambodia townhouses"
python args_dt_load_to_sheet.py -tn "Cambodia townhouses"
python args_dt_dotproperty-2.py -tn "Cambodia townhouses"
python args_dt_dotproperty-mix.py -tn "Cambodia townhouses"